language: cpp

dist: bionic

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install -y libpulse-dev libfftw3-dev libsdl2-dev libsdl2-ttf-dev libsndfile1-dev libgraphicsmagick++1-dev

script:
  - make clean all
