name: Build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        cxx: [/usr/bin/g++, /usr/bin/clang++]

    env:
      CXX: ${{ matrix.cxx }}

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: sudo apt-get install -y libpulse-dev libfftw3-dev libsdl2-dev libsdl2-ttf-dev libsndfile1-dev libgraphicsmagick++1-dev

    - name: Build with make
      run: make all
